### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jsanders** [jwt/ruby-jwt#111]
I was just notified that version 1.5.2 has been released and I'm finding it difficult to evaluate whether or not to make it a priority to upgrade the version I'm using, because there is a lot of changed code and many commits to evaluate. A changelog summarizing the major changes in new versions and what they mean to users would be very nice to have.

I'm willing to work on putting it together, but I'm sure I'll need to bug somebody with lots of questions.

Thanks for the great library!

**Comment by excpt** [comment]
Changelog: https://github.com/jwt/ruby-jwt/releases/tag/jwt-1.5.2

Thanks for the hint.

**Comment by jsanders** [comment]
@excpt: Ah! Totally missed that, thanks for the link.

**Comment by excpt** [comment]
Just fixed that. ;) :beers:

**Comment by jsanders** [comment]
Ah, cheers.
