### ISSUE TITLE
verify_rsa no method 'verify' for class String

### ISSUE THREAD

**Issue by stantoncbradley** [jwt/ruby-jwt#115]
I recently switched my encoding algorithm from HS256 to RS256 and can no longer verify my tokens.  Line 59 in jwt.rb seems to be the problem:

```public_key.verify(OpenSSL::Digest.new(algorithm.sub('RS', 'sha')), signature, signing_input)```

raises a no method error, no method 'verify' for type String.  My public key is a string (no sure what else it should be?), and I don't see verify defined anywhere.  What am I missing?

Thanks!

**Comment by stantoncbradley** [comment]
For context, I'm using Auth0 and Knock, if that helps.

**Comment by stantoncbradley** [comment]
This seems to be a limitation of Knock, not ruby-jwt.  Apologies.

**Comment by AugustoPedraza** [comment]
@stantoncbradley I'm getting the same error, could you please share as you did fix it?

**Comment by stantoncbradley** [comment]
@AugustoPedraza I was using [Knock](https://github.com/nsarno/knock) to pass my JWT to ruby-jwt and Knock didn't support RS256 so it wasn't passing in the proper params.  Adding support for RS256 on Knock fixed my issue.  ruby-jwt works fine for me after that, make sure you are passing the proper params.  It's been awhile since I worked on this so I probably won't be able to give you much more details on what could be wrong with your payload.  Like I said, I think your issue is upstream from ruby-jwt (at least mine was).  Hope that helps!

**Comment by AugustoPedraza** [comment]
@stantoncbradley thanks for your reply. I was getting the same error because I was using an invalid Auth0 workflow to get my JWT.

**Comment by jessecravens** [comment]
@AugustoPedraza can you elaborate on 'using an invalid Auth0 workflow to get my JWT' , Im having the same issue, but fairly certain that Im using a proper workflow, and my JWT validates and signature verifies at jwt.io

**Comment by jessecravens** [comment]
I got this working, as I expected I was passing in the token_public_key incorrectly. #148
