### ISSUE TITLE
Version 1.5.3 breaks 1.9.3 compatibility, but not documented as such

### ISSUE THREAD

**Issue by BanzaiMan** [jwt/ruby-jwt#132]
Yes, I know 1.9.3 has been EOL'd many months ago. It is OK if this is a carefully considered decision. But https://github.com/jwt/ruby-jwt/blob/v1.5.3/ruby-jwt.gemspec does not indicate it.

It should be either indicated as such, or reinstate 1.9.x support.

Upon `require`, it fails:

```sh-session
$ pry
[1] pry(main)> require 'jwt'
SyntaxError: /Users/asari/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/verify.rb:7: unknown type of %string
      %i[verify_aud verify_expiration ...
         ^
/Users/asari/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/verify.rb:7: syntax error, unexpected $end
      %i[verify_aud verify_expiration ...
         ^
from /Users/asari/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by danleyden** [comment]
I wonder if the bump to 1.5.3 from 1.5.2 should have been a major bump
(breaking backwards-compatibility) per semantic versioning?

**Comment by anthony-battaglia** [comment]
Encountered same issue.  Currently forcing 1.5.2 version in Gemfile.  Version bump should have denoted a breaking change.

**Comment by excpt** [comment]
I made 2 PRs to fix the 1.5.3 issues. Mentioned in #133.

PRs: #135 #136 

If you find the time - you can check out the master branch and provide some feedback.

**Comment by excpt** [comment]
Version 1.5.3 yanked.

**Comment by excpt** [comment]
Version 1.5.4 released.

**Comment by sentience** [comment]
:wave: Just dropping by to mention that the yanking of 1.5.3 broke our builds, since the version in our Gemfile.lock is no longer available. I’d suggest that this be considered more carefully before yanking versions post-release in future.
