### ISSUE TITLE
404 at https://rubygems.global.ssl.fastly.net/gems/jwt-1.5.3.gem

### ISSUE THREAD

**Issue by jtangelder** [jwt/ruby-jwt#137]
The Ruby gem returns a 404

```
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/gems/jwt-1.5.3.gem)
```

**Comment by excpt** [comment]
The 1.5.3 version is yanked.

**Comment by shayneoAtNorwood** [comment]
Can you guys please stop yanking old versions. Its really disruptive. Thanks

**Comment by excpt** [comment]
This is the only yanked version and that happended a while ago. Please update your version. This is also mentioned in the README.md.
