### ISSUE TITLE
Adding a CHANGELOG

### ISSUE THREAD

**Issue by guyisra** [jwt/ruby-jwt#140]
Would it be possible to add a simple changelog so it will be easier to know what changed between versions?

**Comment by excpt** [comment]
Do you prefer a file in the sources called CHANGELOG or would it be enough to have a link in the README to the releases section of the github page?

**Comment by guyisra** [comment]
either way, as long as we can see what has changed
If there is only one maintainer/version bumper, a releases section would suffice
