### ISSUE TITLE
JWT 1.5.3

### ISSUE THREAD

**Issue by shakycode** [jwt/ruby-jwt#143]
I'm using Twilio-Ruby 4.2.1 and it has jwt 1.5.3 as a dependency.  When I try to bootstrap a copy of my app with this gem version in Gemfile.lock rubygems cannot find 1.5.3.  I looked at the page on Rubygems.org and it's apparent 1.5.3 is missing.  This is breaking our app.  

Any way to fix this or should we force the gemfile.lock to 1.5.4?

**Comment by excpt** [comment]
Please force it to 1.5.4. Version 1.5.3 is yanked.

**Comment by shakycode** [comment]
@excpt Thanks for the quick response.  I just bumped it to 1.5.4, so far everything tests fine.  Appreciate the help!
