### ISSUE TITLE
Is ruby-jwt thread-safe?

### ISSUE THREAD

**Issue by aarongray** [jwt/ruby-jwt#150]
I'm moving from a threaded web server over to Puma, which is multi-threaded. I don't see in the readme if this gem is thread safe. I glanced through the code and I didn't see any no-no's jumping out at me, but wanted to ask here and see if you folks could give me a definitive answer.

Thanks for this helpful gem!

**Comment by excpt** [comment]
We don't have any kinds of tests to check if this library is thread safe.
Given the current code structure that is basicly just a collection of methods/functions that simply parse input and return output - using puma as a webserver should not give you any trouble.

**Comment by aarongray** [comment]
Good deal, thanks!
