### ISSUE TITLE
Audience Claim broken?

### ISSUE THREAD

**Issue by hirschnase** [jwt/ruby-jwt#151]
This (example code taken fro the github page) throws an Audience Error:

```ruby
hmac_secret = 'test'
aud = ['Young', 'Old']
aud_payload = { :data => 'data', :aud => aud }

token = JWT.encode aud_payload, hmac_secret, 'HS256'

begin
  # Add aud to the validation to check if the token has been manipulated
  decoded_token = JWT.decode token, hmac_secret, true, { :aud => aud, :verify_aud => true, :algorithm => 'HS256' }
rescue JWT::InvalidAudError
  # Handle invalid token, e.g. logout user or deny access
  puts 'Audience Error'
end
```

**Comment by excpt** [comment]
Can you provide your jwt version from the Gemfile, please?

**Comment by excpt** [comment]
This error didn't raise any errors in the test suite because it is not tested for successful validation only for errors.

This line causes the problem.

```ruby
unless @payload['aud'].include?(options_aud.to_s)
```

**Comment by excpt** [comment]
@hirschnase Thanks for reporting!

**Comment by excpt** [comment]
@hirschnase This issue should be fixed now.

If you find the time can you please check your code with the current master branch version of jwt?

Cheers! :)
