### ISSUE TITLE
PHP Libraries

### ISSUE THREAD

**Issue by sagikazarmark** [jwt/ruby-jwt#154]
Hi owners,

I was wondering if you would accept a php jwt library as a contribution (probably together with some framework integration packages).  There are quite a few libraries out there already, yet, i am not really satisfied with their quality which I am really concerned about. Also, the implementations using these libraries are also not really good, so I intend to provide a full solution for the PHP community.

Regards,
Mark

**Comment by excpt** [comment]
HI @sagikazarmark,

send me an mail and I will setup a repo for you and grant you ownership.

We welcome every jwt implementation in any language.
