### ISSUE TITLE
Cannot verify JWT at all??

### ISSUE THREAD

**Issue by deepflame** [jwt/ruby-jwt#177]
Hi everyone,

we are evaluating Auth0 for our service and have problems to get going.
We can verify the token we get on `jwt.io` as you can see here:

<img width="968" alt="screen shot 2016-11-29 at 16 28 55" src="https://cloud.githubusercontent.com/assets/91208/20716329/1b9236c6-b652-11e6-8fec-6f1d4ffce75c.png">

However in the console I get the following:
<img width="1277" alt="screen shot 2016-11-29 at 16 27 02" src="https://cloud.githubusercontent.com/assets/91208/20716351/32864944-b652-11e6-8768-c7478fd9a667.png">

I copied the values from the console into the webpage. So I am pretty confident that they are actually the same.

What can be the problem? Should I reinstall Ruby after my upgrade to macOS Sierra?

**Comment by excpt** [comment]
Can you please provide your Ruby version and jwt version you are using?

After my upgrade to macOS Sierra I had to re-install all my brew installs including rbenv.

**Comment by deepflame** [comment]
Sure!

Ruby 2.3.1
JWT 1.5.6

Yeah, thought that OpenSSL might be messed up now or something. What was the problem you were having?

**Comment by deepflame** [comment]
Yey, I got it to work like this:

```
JWT.decode(token, JWT.base64url_decode(secret), true)
```

Was trying it before with `Base64.decode64` but this did not work.
Happy it works with the provided function :)

**Comment by excpt** [comment]
Ah, ok. The password was the issue.

The password isn't base64 encoded when creating a token with this gem. It needs to be plain text.

**Comment by deepflame** [comment]
This is actually a problem with Auth0's quickstart documentation. Hope they update it soon :)
