### ISSUE TITLE
Why jwt depends on json < 2.0 ?

### ISSUE THREAD

**Issue by GoodMirek** [jwt/ruby-jwt#179]
The latest versions 1.5.5 and 1.5.6 introduced a new dependency "json < 2.0". It causes conflict with our other gems, which use json 2.0.2.
What is the reason to depend on json version below 2.0 ?

**Comment by excpt** [comment]
It is currently compatible with older versions of ruby like 1.9.
Support will be dropped for the older versions by the end of this year.

**Comment by GoodMirek** [comment]
@excpt Thanks for your quick response.
If the constraint was json > 0, would not that be compatible with both 1.9 (e.g. using json 1.8.3) and 2.x (using json 2.0.2) ?

**Comment by excpt** [comment]
I'll try that. Thanks for the hint.

**Comment by excpt** [comment]
I tried that but it will always try to install the latest gem version. This will have to wait until the support ends for older versions of ruby.

**Comment by partydrone** [comment]
Two years later and this is still a restriction. I am putting my app in a Docker image with the latest version of Ruby (2.5). The base image for Ruby comes with json 2.1.0 already installed _as a default gem_, and this is causing errors to show up in my app now: `you have already activated json-2.x but your Gemfile requires 1.8.x`.

Any plans to update this? I looked at the Bitbucket repo, but there's no public issue tracking and I can find no other way to report this issue.…

**Comment by excpt** [comment]
@partydrone, you're right. The ticket was closed and in that it was simply forgotten to update the gemspecs file. Ruby 2.1 and Ruby 2.2 reached the EOL and 2.3 will reach EOL in march 2019.

I think it's now safe to update the version dependency in jwt.

**Comment by jamesstonehill** [comment]
This can be closed. This has been done here:
https://github.com/jwt/ruby-jwt/commit/eba7cd11d091b081ca2ed682daf6854d11406be0#diff-c5e5abace3ae80accf5b0d5f988fe099
