### ISSUE TITLE
Verify JTI Proc

### ISSUE THREAD

**Issue by MPT-ladams** [jwt/ruby-jwt#207]
I'm attempting to use this logic to set & verify the JTI value:

```ruby
jti_raw = [hmac_secret, iat].join(':').to_s
jti = Digest::MD5.hexdigest(jti_raw)
```

When my verify_jti proc is called, I only have access to the @payload['jti'] value passed. How can I access the issued at value from the payload to verify?

Or is this not the intention of how the provided proc is to be used?

Thanks!

**Comment by ab320012** [comment]
@excpt will the following work? (adding iat var and passing to proc) 
```ruby
# jwt/verify.rb
    def verify_jti
      options_verify_jti = @options[:verify_jti]
      jti = @payload['jti']
      iat = @payload['iat'] 
      if options_verify_jti.respond_to?(:call)
        raise(JWT::InvalidJtiError, 'Invalid jti') unless options_verify_jti.call(jti, iat)
      elsif jti.to_s.strip.empty?
        raise(JWT::InvalidJtiError, 'Missing jti')
      end
    end

```

**Comment by excpt** [comment]
@MPT-ladams Would that be a fitting solution to access the payload of the token?
