### ISSUE TITLE
Support versions outside 2.1

### ISSUE THREAD

**Issue by ilanbiala** [jwt/ruby-jwt#209]
Does this library support versions outside of Ruby 2.1?

**Comment by excpt** [comment]
We run our tests against 2.2, 2.3 and 2.4 on travis and all pass. You can have a look at them here: https://travis-ci.org/jwt/ruby-jwt

**Comment by ilanbiala** [comment]
Ah okay, I looked at https://github.com/jwt/ruby-jwt/blob/master/ruby-jwt.gemspec#L16 and saw a bound version. Maybe it should be `>= 2.1` then?

**Comment by excpt** [comment]
Yes. This should be `>= 2.1`. Thanks for that hint.
