### ISSUE TITLE
Ed25519 support planned?

### ISSUE THREAD

**Issue by Justin-Maxwell** [jwt/ruby-jwt#217]
Hi.

Are there plans to incorporate Ed25519?  (via RbNaCl presumably).

Cheers.

**Comment by excpt** [comment]
@Justin-Maxwell 

Sure, this would be an awesome addition. For a more complete JWT spec implementation.

Setting this to "up for grabs"

**Comment by excpt** [comment]
@Justin-Maxwell This feature will be added with 2.1.0. See #229.
