### ISSUE TITLE
The README says it uses an algorithm by default

### ISSUE THREAD

**Issue by alebian** [jwt/ruby-jwt#226]
Hi, the README says it uses HS256 by default but since https://github.com/jwt/ruby-jwt/pull/184 you must provide an algorithm option

We should remove the word "default" from readme

**Comment by excpt** [comment]
This is also mentioned in #227 and explains this in more detail. Discussion will continue there.

**Comment by excpt** [comment]
You are correct, I mixed things up. #227 played tricks on my mind. Reopen.
