### ISSUE TITLE
There is no "typ" header in version 2.0.0

### ISSUE THREAD

**Issue by ptarud** [jwt/ruby-jwt#233]
Why there is no `type` header in version 2.0.0 ?

**Comment by excpt** [comment]
The `typ` header field is optional.

See: #174 and https://tools.ietf.org/html/rfc7519#section-5.

Does this change cause any issues for you?

**Comment by ptarud** [comment]
Not, but I think that for other people could be generate a issue if they use other media types in addition to JWT token. So, I think would be better to include "typ" header on JWT token.

**Comment by lleger** [comment]
After upgrading to 2.0, my tests were failing. Took me a second to realize it was because of this change. The token fixture I had included the `typ` param but new tokens did not — thus the failure. This is a fine change, so I’m chiming in here to help anyone else searching for test failures after upgrading to 2.0.

**Comment by excpt** [comment]
@lleger Thank you very much for offering help. 🥇

**Comment by thegreyfellow** [comment]
Hi, I just want to know if starting `v2.2.1` the JWT created will always include in the header by default the entry : 

`"typ": "JWT"
`

 or not?

**Comment by Seitk** [comment]
another way around, JWT was a default header before 2.0.0
removed by this PR
https://github.com/jwt/ruby-jwt/pull/174/files

**Comment by chriso0710** [comment]
I would like to comment on this (unfortunately) closed issue. 
It does not make much sense to me to remove the "typ" from the default headers. I think, the typ should be set by default to "JWT". A missing typ header is prone to causing all kinds of problems and took me a couple of hours to debug in a netlify environment. See details here:
https://community.netlify.com/t/identity-role-based-access-control-across-subdomains/29957/12

**Comment by eric-hemasystems** [comment]
FYI, Auth0 started rejecting JWT tokens without the `typ` specified. Specifying it manually restored functionality.
