### ISSUE TITLE
JSON support 

### ISSUE THREAD

**Issue by msroot** [jwt/ruby-jwt#246]
I dint see anywhere in the ready me about Json Support 
So is it official Json data supported? 

```ruby 

data = {foo: 'bar'}
exp_payload = { :data => data, :exp => 1.month.from_now.to_i }
hmac_secret = "yo"

token = JWT.encode exp_payload, hmac_secret, 'HS256'
# => "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImZvbyI6ImJhciJ9LCJleHAiOjE1MTIwNzQ4Njl9.b7vPoy6oU4W0x0qtcMm0cDjg3uMOFBY5mbL1Bj0BkeQ"


JWT.decode token, hmac_secret, true, { :algorithm => 'HS256' }
# => [{"data"=>{"foo"=>"bar"}, "exp"=>1512074869}, {"typ"=>"JWT", "alg"=>"HS256"}]

```

**Comment by mod** [comment]
I am also looking for the implementation of
https://tools.ietf.org/html/rfc7515#section-7.2.1

General JWS JSON Serialization Syntax
with multiple signature support

**Comment by msroot** [comment]
@ab320012 Sure we can close the issue then. I just dint see it in read me anywhere
