### ISSUE TITLE
Issued at validation

### ISSUE THREAD

**Issue by Jack12816** [jwt/ruby-jwt#247]
Hey guys, first off: thanks for this great library!

I have a common question, or maybe I don't get the point right now. So lets say a token was 
issued a hour before now. (Say 1pm) And now is 2pm. Why is the verify_iat checking if iat is
newer than now? 

```ruby
if .. @payload['iat'].to_f > (Time.now.to_f + leeway)
  raise ..
end
```

I mean yeah, the leeway could be a hour or more, but isn't this exactly what nbf (not before) 
should take care of? I found this "issue" (if I got it right) on a common test case. (iat -1h, exp: +2h, now is in between)

Could someone explain this to me, or confirm a bug?

**Comment by excpt** [comment]
@Jack12816 Thanks for reporting.

A very interesting point you bring up. I will read the specs again and revalidate the whole thing. Maybe you're on to something.

**Comment by Jack12816** [comment]
@excpt Ping. :) Whats the current state?

**Comment by excpt** [comment]
@Jack12816 I'm back from vacation. I look into this and I think I can give you a clear answer by friday.

**Comment by Jack12816** [comment]
@excpt Ping. Many fridays passed :D

**Comment by excpt** [comment]
@Jack12816 Thanks for the reminder. :)

**Comment by dmitry-vakhnenko** [comment]
Ping ;-)

**Comment by excpt** [comment]
Conclusion: @Jack12816 you are correct. This is a bug. 

The `iat` claim has no concept of a leeway. `nbf` allows a small leeway. 

As mentioned the `nbf` should be the claim that ensures the validity of the token in that case.

**Comment by LeZuse** [comment]
How are we supposed to deal with desynchronized server clocks then? It's what the leeway was designed to do, right? Are we supposed to direct the generation-site that they **must** include a `nbf` claim instead?
