### ISSUE TITLE
Add support for headless token

### ISSUE THREAD

**Issue by GabKlein** [jwt/ruby-jwt#251]
As the header provide useful information such as the algorithm used to encode the token, it can also be used against the system. In my case I'm would like to use headless token and force the algorithm to decode a token.

**Comment by excpt** [comment]
In order to check if the correct algorithm is set use the verify logic that is built in this gem.

```ruby
# force check for algorithm HS256 -> otherwise throw an exception
JWT.decode token, secret, true, {algorithm: 'HS256'} 
```

**Comment by excpt** [comment]
@GabKlein Is still relevant? Is using the decode and verification logic a viable solution?
