### ISSUE TITLE
NameError: uninitialized constant JWT::Algos::Eddsa::RbNaCl

### ISSUE THREAD

**Issue by yivo** [jwt/ruby-jwt#258]
Steps to reproduce:

1. Run `JWT.encode({}, OpenSSL::PKey::RSA.generate(2048), 'ED25519')`

This error occurs when you supply invalid key type to encoder.

**Comment by excpt** [comment]
Thanks for reporting. What version of this gem are you using?

**Comment by yivo** [comment]
@excpt The latest one: 2.1.0

**Comment by excpt** [comment]
In order to use the ED25519 algorithm it is required to have the rbnacl gem installed. See instruction for usage in the README.md.
