### ISSUE TITLE
TypeError: no implicit conversion of OpenSSL::PKey::RSA into String

### ISSUE THREAD

**Issue by yivo** [jwt/ruby-jwt#259]
Steps to reproduce:

1. `JWT.encode({}, OpenSSL::PKey::RSA.generate(2048), 'HS384')`

**Comment by excpt** [comment]
Thanks for reporting. What version of this gem are you using?

**Comment by ab320012** [comment]
You are specifying a HMAC algo but then trying to sign it with a RSA key which is causing the issue

**Comment by yivo** [comment]
@excpt It is 2.1.0.

@ab320012 I thought it should work with RSA key. Isn't it?

**Comment by yivo** [comment]
It works if I provide RSA key as string in PEM format:

`JWT.encode({}, OpenSSL::PKey::RSA.generate(2048).to_pem, 'HS384')`

**Comment by ab320012** [comment]
@yivo, @excpt will throwing error if hmac input is not a String okay in this case ?

**Comment by yivo** [comment]
@ab320012 OK, so in this case it is fine!

@excpt I think we can close the issue.

Thank you for the help!
