### ISSUE TITLE
Ruby JWT Token

### ISSUE THREAD

**Issue by Anjana93** [jwt/ruby-jwt#265]
how to extract Private key from x509 certificate in Ruby Programming?

**Comment by excpt** [comment]
Hi @Anjana93,

This is not part of the ruby JWT project. I'm referring you to a link on stack exchange that might help you: https://stackoverflow.com/questions/31612841/ruby-how-to-extract-public-rsa-private-and-ca-keys-from-pfx-file-on-ruby
