### ISSUE TITLE
Claim and signature validations without raising exceptions

### ISSUE THREAD

**Issue by jec** [jwt/ruby-jwt#270]
My company has a fork of this project that uses `ActiveModel::Validations` to inform of validation failures, rather than raising exceptions. The goal of our fork is to allow the existing behavior while also providing the alternate behavior by adding `require: 'jwt/activemodel'` to the line in the `Gemfile`.

Is there any interest in our contributing these changes back to this project?

**Comment by excpt** [comment]
Hi @jec,

This is a requested feature. 👍 

I'd love to see you approach.

If you wan't to open a PR I would create a fitting branch.

**Comment by anakinj** [comment]
The new `JWT::EncodedToken` provides this kind of API.
