### ISSUE TITLE
signature validation using decode method for JWT

### ISSUE THREAD

**Issue by ndshendage** [jwt/ruby-jwt#271]
I have gone through the docs of this gem but not understanding to use the decode method actually i need to verify the signature of my jwt token i am having.
So trying to use the decode method as suggested in it but getting an error for my 'scret_key'
its always, NoMethodError Exception: undefined method `verify' for "secret_key"
Would like to know how to use it while verifying the signature of Jwt.

Thanks in advance

**Comment by excpt** [comment]
Hi @ndshendage,

the signature check happens automaticly when passing the 3rd argument `verify` = `true`. There is no need to check your signature by hand as it is already taken care of.
Then the JWT gem checks the signature of your token.
If it fails an exception of `DecodeError` is thrown.

```ruby
token = 'my.jwt.token'
password = 'super secret'
my_algo = 'HS256'
verify = true

begin
  JWT.decode(token, password, verify, {algorithm: my_algo})
rescue DecodeError
  # error that happend during verification of the token
end
```

**Comment by ndshendage** [comment]
Thanks for your time actually i was using much older gem version of it and i think signature validation was not working with it. 
JWT.decode(token, password, verify, {algorithm: my_algo})
above method was accepting only 3 params and error if we pass 4 params like above.
And for verification of signature it was always giving me error but when i updated my gem version in other project and proceed same way i was able to do all.

Thanks

**Comment by excpt** [comment]
@ndshendage Thanks for the feedback.
