### ISSUE TITLE
Audience as an array - how to specify?

### ISSUE THREAD

**Issue by mahemoff** [jwt/ruby-jwt#276]
The README says an array is possible for `aud`. I specified an array of possible audiences:

    verify_aud: true, aud: ['client1', 'client2', 'client3']

I'm seeing this when "client1" (for example) is passed in as aud:

      "Invalid audience. Expected ["client1", "client2", "client3"], received client1

Maybe I'm specifying the array wrong, but I'm not sure how else it would be done.

**Comment by excpt** [comment]
Hi @mahemoff,

can you please specify the jwt version you're using?

**Comment by excpt** [comment]
@mahemoff kijdr<elkftrkijgxyjkivgfds öjlkoidsevrgf mj-ö lkdnfhzbgrt  
jgftjgfcjg cvkj
