### ISSUE TITLE
Inconsistent handling of payload claim data types

### ISSUE THREAD

**Issue by jamesstonehill** [jwt/ruby-jwt#282]
When passing in a `Time` object as the value of the `exp` claim, if the key of the payload is a string it raises a `JWT::InvalidPayload` error. When using the symbol as the key, it does not raise the error. 

### When the `exp` claim key is a string
```ruby
exp_payload = { 'exp' => Time.now }
token = JWT.encode exp_payload, 'asdf'
# => JWT::InvalidPayload: exp claim must be an integer
```

### When the `exp` claim key is a symbol
```ruby
exp_payload = { exp: Time.now }
token = JWT.encode exp_payload, 'asdf'
# => "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOiIyMDE4LTA5LTA3IDEzOjA3OjU0ICswMTAwIn0.9PxmdZFISuVXQQTDA6bw4vavK428o0R1WvcIZ5np6Lg"
```

Symbol and string keys in the payload should be handle in a consistent way.

**Comment by excpt** [comment]
Hi @jamesstonehill,

thanks for the detailed report. Can you specify your ruby-jwt version you're using?

**Comment by jamesstonehill** [comment]
@excpt yeah, sorry I should have included that in the report. I'm using the latest release, 2.1.0.

**Comment by excpt** [comment]
@jamesstonehill can you check against the current master branch if #293 fixed this issue for you, please?

**Comment by jamesstonehill** [comment]
@excpt yeah this is fixed in the current master.
