### ISSUE TITLE
Could you add fixtures for PS-algorithms in specs?

### ISSUE THREAD

**Issue by lolgear** [jwt/ruby-jwt#304]
Hi!

It would be nice if you add fixtures for PS-algorithms in specs.

Thanks!

**Comment by bmorrall** [comment]
I've just had a look through the code; there's a number of specs for PS-algorithms, and they're successfully using the rsa fixtures:

- https://github.com/jwt/ruby-jwt/blob/main/spec/jwt/jwt_spec.rb#L258

What fixtures are you specifically looking for?

**Comment by anakinj** [comment]
PS algos are covered. Closing this one.
