### ISSUE TITLE
Adding support for 'hd' hosted domain string

### ISSUE THREAD

**Issue by bubbaspaarx** [jwt/ruby-jwt#314]
On a couple of occasions I have needed to validate the hosted domain returned by services like google-login. At the moment I am doing a manual check once the token has been validated but it would be great to have a 'verify_hd' option within JWT for these situations. Happy to write a pr but will need some assistance creating the correct JWT::Error message. 

Many thanks

**Comment by excpt** [comment]
@bubbaspaarx This won't be implemented into this gem. The `hd` claim is not an official reserved JWT claim. Only these will be handled by default in this gem.

There is a list of additional reserved claims for different use cases. https://www.iana.org/assignments/jwt/jwt.xhtml#claims

It looks like the `hd` claim is a private one.
