### ISSUE TITLE
need to `require 'forwardable'` to use `Forwardable`

### ISSUE THREAD

**Issue by mikegee** [jwt/ruby-jwt#316]
I get an error from JWT 2.2.0 on Ruby 2.3 and 2.5.

`JWT::JWK::RSA` extends `Forwardable`, but there is no `require 'forwardable'` in the gem. I worked around this in my script by explicitly requiring forwardable.

This fails:
```
% docker run --rm -it ruby:2.3 ruby -e 'class MyClass; extend Forwardable; end'
-e:1:in `<class:MyClass>': uninitialized constant MyClass::Forwardable (NameError)
	from -e:1:in `<main>'
```

This doesn't fail:
```
% docker run --rm -it ruby:2.3 ruby -e 'require "forwardable"; class MyClass; extend Forwardable; end'
```

**Comment by excpt** [comment]
Which version of openssl is installed in you environment?

Please try to update it to version ~> 2.1.

**Comment by mikegee** [comment]
Looks like the official Ruby 2.3 docker image comes with OpenSSL 1.1.1:

```
% docker run --rm -it ruby:2.3 ruby -ropenssl -e'puts OpenSSL::VERSION'
1.1.1
```

I'm not interested in updating a system library, nor do I understand how it is related, since `require 'forwardable'` resolves the problem.

**Comment by btyy77c** [comment]
I've had the same problem: https://github.com/railscltgroup/firebase_auth/blob/master/lib/firebase_ruby_auth.rb
JWT 2.2.0 and Ruby 2.6.2

I have a similar file in a personal Rails app.  I don't get any errors in my Rails app. However, when I'm just working on this gem, the `require 'jwt'` command errors out. `require 'forwardable'` seems to fix the error.

**Comment by excpt** [comment]
@mikegee @btyy77c 

Version 2.2.1 just released. This should fix he missing dependency issue for you.

Thanks for the detailed reporting!
