### ISSUE TITLE
Can we change the separator character?

### ISSUE THREAD

**Issue by benjaminb10** [jwt/ruby-jwt#321]
Can we change the separator character?
For instance use dash '-' instead of point '.'
For having this kind of token:
http://myapp.com/orders/401?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9-eyJkYXRhIjp7ImlkIjo0MDF9fQ-5QP99XqVuhorG1k_CpIKWt0e5f400rPjCwgphgDrZrg

Instead of:
http://myapp.com/orders/401?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjo0MDF9fQ.5QP99XqVuhorG1k_CpIKWt0e5f400rPjCwgphgDrZrg

**Comment by hesalx** [comment]
Period (`.`) is by RFC https://tools.ietf.org/html/rfc7519#appendix-A.1
Is there any issue with processing the token before passing in to the standardized library? 
```ruby
rfc_token = raw_token.gsub('-', '.')
JWT.decode(rfc_token)
```
