### ISSUE TITLE
eval() used in Forwardable limits usage in iOS App Store

### ISSUE THREAD

**Issue by jtara** [jwt/ruby-jwt#324]
I notice that *Forwardable* uses *eval()*.

This makes the resulting product not eligible for inclusion in the iOS App Store, when building a native app using Rhodes, RubyMotion/DragonRuby, or other Ruby-based mobile app platforms.  (FWIW, my use case is Rhodes platform.)

The iOS App Store does not permit the use of *eval()* by interpretive languages. (Ruby-based mobile app frameworks compile to Ruby Bytecode at build time.)

I wonder if it is possible to eliminate this dependency?

`ruby-jwt` is an attractive solution for such environments, because of it's relative simplicity and lack of extensive dependencies vs e.g. https://github.com/nov/json-jwt (I use json-jwt in API server code, but use ruby-jwt in a mobile app because it is easier to deploy there.)

For my own case, I don't need RSA support, which is the only place where *Forwardable* is used, so I will comment-out require for RSA.

**Comment by anakinj** [comment]
Thanks for the detailed description. There is no point of using the convenience of Forwardable if there are these kind of downsides.

Made a PR for removing the dependency.
