### ISSUE TITLE
Need to use `symbolize_keys` everywhere!

### ISSUE THREAD

**Issue by rahulbajaj0509** [jwt/ruby-jwt#330]
I am trying to use the `jwks_loader` function which looks something like:

```ruby
    response = RestClient::Request.execute(
      :url => Setting['oidc_jwks_url'],
      :method => :get,
      :verify_ssl => true
    )
    jwks_keys = JSON.parse(response)['keys']
    { keys: jwks_keys.map(&:symbolize_keys) }
```

I don't like the fact that I need to use the `symbolize_keys`(rails method), can we check if the keys for the hash has symbols or strings, if strings then we can convert them into symbols.

I am not sure if this even makes any sense, but if it looks reasonable and valid then I would like to contribute to it :)

**Comment by jtara** [comment]
You could use:

`jwks_keys.with_indifferent_access`

You would need to load ActiveSupport. If you've a Rails project, it's already there.

If not Rails, you may need to add ActiveSupport as I do in my Sinatra-based API work.

I don't think it would be good to change it internally, as it would create a dependency on ActiveSupport.

**Comment by excpt** [comment]
I agree with @jtara. This is an implementation detail specific to the application of @rahulbajaj0509. The ActiveSupport dependency won't be introduced.
