### ISSUE TITLE
Wrong `alg` used in header for Ed25519 keys

### ISSUE THREAD

**Issue by zblach** [jwt/ruby-jwt#334]
The example tokens in this library use `"alg": "ED25519"`, but the related spec seems to suggest that it be `"EdDSA"` instead.

https://tools.ietf.org/html/rfc8037#appendix-A.4

**Comment by anakinj** [comment]
I think you are correct. Now I wonder how we could make this right. The feature has been out in the wild for a pretty long time already and encoded tokens get this incorrect `alg` header. 

I would suggest:
- Not to change the generated `alg` header (The decoding should not care about the given header anyway)
- Start supporting the correct algorithm (EdDSA) in the decode method

**Comment by mattgibson** [comment]
>Not to change the generated alg header (The decoding should not care about the given header anyway)

I just ran into this when trying to use a Ruby-generated token in an Elixir app. The Elixir library is using the `alg` header to choose the decryption algorithm and is case-sensitive, so `ED25519` causes a signature error as it can't work out how to handle it, but `Ed25519` works.

**Comment by anakinj** [comment]
Just out of curiosity, what Elixir library is this?

My biggest concern is that if it is just changed to something else for example old ruby-jwt<-> new ruby-jwt compatibility will at least break.

**Comment by anakinj** [comment]
If you are in control of the token generation you could change the constant controlling this locally:
`JWT::Algos::Eddsa::SUPPORTED = ["Ed25519"]`

**Comment by mattgibson** [comment]
I was using [Joken](https://github.com/joken-elixir/joken), but the underlying low level library it uses is [JOSE](https://github.com/potatosalad/erlang-jose)

**Comment by mattgibson** [comment]
>If you are in control of the token generation you could change the constant controlling this locally:
JWT::Algos::Eddsa::SUPPORTED = ["Ed25519"]

Yes, I found that and it worked when generating the tokens. I think for now I'm going to fork the gem and ensure it will decrypt both `Ed25519` and `ED25519` tokens. Thanks for the pointer!

**Comment by anakinj** [comment]
But apparently this Joken component is expecting the EdDSA algorithms to have the exact curve used in the `alg` field. So changing the alg to `EdDSA` will not make this gem compatible either.

**Comment by mattgibson** [comment]
Ah, that's a good point. Possibly Joken is not implementing the RFC correctly either.

**Comment by anakinj** [comment]
Btw. I think the easiest workaround is just to monkeypatch the `JWT::Algos::Eddsa::SUPPORTED` constant. No need for forks.

```
require 'jwt'
require 'rbnacl'

JWT::Algos::Eddsa::SUPPORTED = ["Ed25519"]

signing_key = ::RbNaCl::Signatures::Ed25519::SigningKey.new('a'*32)
token = JWT.encode({con: 'tent'}, signing_key.verify_key, 'Ed25519')
```

**Comment by renato-zannon** [comment]
I was looking into actually generating the tokens with the correct `"alg"` value (in my case, because I wanted them to be verifiable by [ruby-jose](https://github.com/potatosalad/ruby-jose)), and had to modify a bit more than just the constant.

Specifically, the [conditionals](https://github.com/jwt/ruby-jwt/blob/2cea14fdae439773fafc59640178e5cf7a0af8a4/lib/jwt/algos/eddsa.rb#L11) on `eddsa.rb` were comparing `alg` to the key primitive (`"EdDSA"` vs `:ed25519`) and raising `IncorrectAlgorithm` as a result.

I've made a quick monkeypatch on my side to override this and allow `EdDSA` anyway. Is this something that would be sensible to add to the project? If so, I would be happy to open a PR.

**Comment by anakinj** [comment]
I would suggest introducing a breaking change and change the header handling to be inline what the RFC and world is expecting for the version 3.0.0

**Comment by wparad** [comment]
Wow, still broken in 2024

**Comment by SebastianPoell** [comment]
Instead of redefining the constant (which triggers a Ruby warning), a way of patching this without warning would be to remove the constant and set it again:

```ruby
JWT::JWA::Eddsa.send(:remove_const, "SUPPORTED")
JWT::JWA::Eddsa.const_set("SUPPORTED", ["Ed25519"])
```

**Comment by anakinj** [comment]
There has been some work done to extract the algorithms that require external dependencies to separate gems. EdDSA being the first one that got that treatment. The goal is to remove the algorithm without native support from this gem in the future.

Check out https://rubygems.org/gems/jwt-eddsa for eddsa support with a alg header according to the rfc.

**Comment by anakinj** [comment]
This algorithm is now only supported via the gem mentioned.
