### ISSUE TITLE
cannot load such file -- jwt

### ISSUE THREAD

**Issue by ICloud0114** [jwt/ruby-jwt#339]
Traceback (most recent call last):
	2: from token.rb:1:in `<main>'
	1: from /Users/***/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/***/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- jwt (LoadError)

########################################################################
require 'jwt'

payload = { data: 'test' }

token = JWT.encode payload, nil, 'none'

puts token

decoded_token = JWT.decode token, nil, false

puts decoded_token

**Comment by victorhazbun** [comment]
seems like you did not installed the gem. Please double check.

**Comment by excpt** [comment]
@ICloud0114 Do you still have any issues using the gem?

**Comment by excpt** [comment]
Closed due to inactivity.
