### ISSUE TITLE
What is secret when using RSA keypair

### ISSUE THREAD

**Issue by schowdhury** [jwt/ruby-jwt#340]
Hello,  curious what is the "secret" per JWT spec when using RSA keypair

**Comment by cpb** [comment]
A private key. Check my fork of omniauth-jwt for test cases as examples of
how it should behave

**Comment by cpb** [comment]
IE: public key decodes https://github.com/trykinside/omniauth-jwt/blob/master/spec/lib/omniauth/strategies/jwt_spec.rb#L120

private key encodes: https://github.com/trykinside/omniauth-jwt/blob/master/spec/lib/omniauth/strategies/jwt_spec.rb#L102

**Comment by cpb** [comment]
Or even this very project's readme example specs

https://github.com/jwt/ruby-jwt/blob/be861685af7975fefe43e5eccfe2a552aa818cb6/spec/integration/readme_examples_spec.rb#L32-L43

**Comment by cpb** [comment]
@schowdhury does that help?
