### ISSUE TITLE
Release with support for RSA.import for ruby < 2.4 hasn't been released

### ISSUE THREAD

**Issue by hyunskang** [jwt/ruby-jwt#347]
It looks like a new version with [changes](https://github.com/jwt/ruby-jwt/pull/333) to support RSA.import for ruby < 2.4 hasn't been released yet despite the changes being in master.

Would it be possible to know when it will be released?

Thank you

**Comment by excpt** [comment]
Will be included in the next 2.2.2 release. Currently in the works. Will keep you up to date when the new release is available.

**Comment by hyunskang** [comment]
@excpt Thank you very much!

**Comment by excpt** [comment]
@hyunskang Version 2.2.2 released. 🎉
