### ISSUE TITLE
JWT gitlab OmniAuth provider setup support

### ISSUE THREAD

**Issue by rinshadka** [jwt/ruby-jwt#354]
Hi, how to integrate jwt authentication with gitlab. Is there any provider for jwt to register. Or should we need to create our own service with jwt libraries?

Gone through this link - https://github.com/mbleigh/omniauth-jwt#usage, Is there any documentation or reference regarding this implementation?

Please help
Thanks

**Comment by anakinj** [comment]
Hi @rinshadka 

Not totally sure if I understand your question or problem, but the ruby-jwt GEM is used only to encode and decode JWT tokens using various algorithms.

It's not per se an authentication provider.

**Comment by phlegx** [comment]
@rinshadka related issue #340 where ruby-jwt is used with `omniauth-jwt`. You have to ask the creator of `omniauth-jwt` for documentation or reference regarding the omniauth-jwt gem.

**Comment by anakinj** [comment]
Closing this. If there are some needs for improving the documentation we are open for suggestions.
