### ISSUE TITLE
undefined method `verify' for nil:NilClass when validate a JWT with JWK

### ISSUE THREAD

**Issue by danielweil** [jwt/ruby-jwt#383]
I am trying to validate my JWT token using jwk, the same way it is present in the documentation, but I keep receiving the error:

"undefined method `verify' for nil:NilClass"

Can someone help me?
I get my jwk from my keycloak server, and it is a hash, with the right format.

![image](https://user-images.githubusercontent.com/44274213/98964109-2e6ef100-24e7-11eb-8e9a-789da9f52895.png)

![image](https://user-images.githubusercontent.com/44274213/98964153-3af34980-24e7-11eb-91fa-d9434926ed45.png)

Thanks!

**Comment by anakinj** [comment]
Looks like you are using version `1.5.6` of the gem. The JWK support was introduced in `2.2.0`.

**Comment by anakinj** [comment]
Also the latest released version expect the keys to be symbols. The next release will have support for a mix of strings and symbols. Until that you need to symbolize the keys in the hash given to the decode method.

**Comment by anakinj** [comment]
Closing this. Please reopen if there are some issues with this and the latest versions of the GEM.
