### ISSUE TITLE
How to use a 'signing key' as used by next-auth

### ISSUE THREAD

**Issue by recurser** [jwt/ruby-jwt#389]
I'm trying to use [next-auth](https://next-auth.js.org/providers/apple#example-jwt-code) on the frontend backed by a Rails API. The JWT tokens generated by the frontend use a `signingKey` ([see docs](https://next-auth.js.org/warnings#jwt_auto_generated_signing_key)). The key looks like this:

```
$ jose newkey -s 256 -t oct -a HS512
{"kty":"oct","kid":"kigxq6S4B7X4-wTxbqEJMYLYVid-BjW4SZMMm6wSC3c","alg":"HS512","k":"ghBlGxKq9CcDYDG7XUHmquoBc-mrMXWfpZcPYnMihBQ"}
```

I can't get the tokens generated by the frontend to verify in Ruby (`Signature verification raised`), and I'm unsure how to plug this key into `ruby-jwt`. The tokens seem to verify ok in [jwt.io](https://jwt.io/). Any advice as to how I should use this kind of JSON key in addition to (or instead of?) the secret in `ruby-jwt`?

On the ruby side I'm doing this:

```
JWT.decode(token, secret, true, { algorithms: ['HS512'] })
```

**Comment by recurser** [comment]
I've figured this out - the signing key created via `jose newkey -s 256 -t oct -a HS512` is using type `oct`, but the `ruby-jwt` [docs](https://github.com/jwt/ruby-jwt/blob/ef8718b25e6b81d65312a0ef0a7f5fe8b6eae96b/README.md#json-web-key-jwk) state that it `Currently only supports RSA public keys`.

To use `ruby-jwt` with `next-auth`:

1. Creating an `rsa` signing key (`jose newkey -t rsa`)
1. Add the `signingKey` as a JSON string in `next-auth` config (see [docs](https://next-auth.js.org/warnings#jwt_auto_generated_signing_key)).
1. Decode in ruby via:
    ```
    jwks = { keys: [<INCLUDE SIGNING KEY HERE AS A RUBY HASH, NOT A JSON STRING>] }
    JWT.decode(token, secret, true, { algorithms: ['PS256'], jwks: jwks }) 
    ```

**Comment by exocode** [comment]
Hi @recurser . NextAuth dropped the support of `signingKey`s in V4. Did you upgrade your Rails app? If yes, how did you do that? Would be nice if you can provide some example code. I thought maybe dropping ruby-jwt and implementing some jwt gem which supports the encryption method NextAuth suppprts. 
Thank you in advance

**Comment by recurser** [comment]
@exocode I actually ended up switching to using Go for the API, so I don't use `ruby-jwt` any more
