### ISSUE TITLE
JWT::JWK::EC needs `require 'forwardable'`

### ISSUE THREAD

**Issue by mengkuan** [jwt/ruby-jwt#392]
Using ruby 2.7.1 and trunk version of jwt (dc946fa), I get the following error when trying to verify a token:

```
lib/jwt/jwk/ec.rb:6:in `<class:EC>': uninitialized constant JWT::JWK::EC::Forwardable (NameError)
```

Adding `require 'forwardable'` to the top of `ec.rb` resolves this.

**Comment by anakinj** [comment]
Thanks for the report.

There are some changes to the new algorithms in the making, this also removes the dependency to the forwardable module.

https://github.com/jwt/ruby-jwt/pull/388

**Comment by mengkuan** [comment]
I see. In this case I'll close this ticket. Thanks!
