### ISSUE TITLE
NameError: uninitialized constant JWT::JWK

### ISSUE THREAD

**Issue by nandini-klocrix** [jwt/ruby-jwt#403]
Hi, 
I am verifying apple login and verifying token on server side. I am following this doc for reference:
https://styrk.medium.com/handle-apple-sign-in-on-the-server-ruby-on-rails-78f0d3b4991d

But when I call `jwk = JWT::JWK.import` I get error "NameError: uninitialized constant JWT::JWK"

I am also following this gem readme file and getting same error when I run `jwk = JWT::JWK.new(OpenSSL::PKey::RSA.new(2048))` in console

I am also doing require 'jwt' in console.

Thanks

**Comment by anakinj** [comment]
Hello. What version of the jwt gem are you using?

**Comment by nandini-klocrix** [comment]
jwt (1.5.6)

**Comment by anakinj** [comment]
Think that is the issue. The JWK features were added in version 2.2.0 (i think)

**Comment by nandini-klocrix** [comment]
ok, thanks! will try with this version and update it here.

**Comment by anakinj** [comment]
Closing this. The JWK features were not present in 1.5.6.
