### ISSUE TITLE
Version number & changelog on web page is radically out of date

### ISSUE THREAD

**Issue by masukomi** [jwt/ruby-jwt#407]
on <https://jwt.github.io/ruby-jwt/> it currently says 

> Current version: 1.5.6

and the last changelog update was 2016-09-19

**Comment by excpt** [comment]
Yes. This page could use some love. It got left behind the code issues. There is already something brewing in the background but I think this will take until June.

**Comment by anakinj** [comment]
#629 changed the github pages to get updated with the yard docs from the main branch.
