### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by bouk** [jwt/ruby-jwt#409]
Hello,

I'd like to use the EC support for JWKs, could you release a new version of the gem?

Thanks! ✨

**Comment by butsjoh** [comment]
I am also waiting on a bump cause i cannot export the private part of the key ```jwk.export({include_private: true})``` cause that has been added on in the main branch and not in the latest release (2.2.2)

**Comment by excpt** [comment]
Hey @bouk and @butsjoh 

Wanted to  let you know that version 2.2.3 has been released.

**Comment by butsjoh** [comment]
thnx !!! much appreciated 👍
