### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by joseneto** [jwt/ruby-jwt#429]
Ruby: 3.0.1
Rails 6.1.4
JWT: 2.3.1

`JWT.decode "111.111.111", nil, false`

works fine if I remove the dots

`JWT.decode "111111111", nil, false`

Give me the error -> ArgumentError: wrong number of arguments (given 2, expected 1)

**Comment by joseneto** [comment]
The problem was the json version, after updated everything works fine

**Comment by thomasdarde** [comment]
which json version did you use @joseneto ?

**Comment by joseneto** [comment]
Hi @thomasdarde I using now version 2.5.1

`gem 'json', '~> 2.5.1'`
