### ISSUE TITLE
JWT to memory

### ISSUE THREAD

**Issue by xhostcom** [jwt/ruby-jwt#436]
Hi not an issue as such but has anyone used this gem and saved token in memory rather than local storage/cookies in rails? Is there a way of doing that?

Thanks

**Comment by anakinj** [comment]
Think this gem is not really related to storing tokens. But one way to store tokens in memory would be to have a class variable as storage. This approach is probably only suitable if the tokens are specific for the application and is not that dynamic, like depending on the user of the application.

```
module MyMemoryTokenCache
  def self.cached_token
    @cached_token = nil if @cached_token.expired?

    @cached_token ||= fetch_token
  end

  def self.fetch_token
    # Generate/fetch the token from 3rd party
  end
end
```

**Comment by xhostcom** [comment]
OK great thanks
