### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by bouk** [jwt/ruby-jwt#468]
Hi there,

Since the openssl 3.0.0 gem is out, this gem is not compatible without this fix: https://github.com/jwt/ruby-jwt/pull/452

Could you please cut a new version?

Thank you!

**Comment by arkadiyt** [comment]
+1 to this - was hoping to use the new "multiple keys" support but it's not available yet

**Comment by excpt** [comment]
Version 2.4.1 is released. Have you had the time to test it?
