### ISSUE TITLE
Encode output with extra quote

### ISSUE THREAD

**Issue by vincentlkl** [jwt/ruby-jwt#469]
payload = "test"
token = JWT.encode payload, rsa_private_key, 'RS256'

when I paste the token to 
https://dinochiesa.github.io/jwt/
I am getting 
"test"

It cannot decode it to as a raw text
test 
** without the double quote

**Comment by anakinj** [comment]
The behaviour you are seeing is in line with the [JWT RFC](https://datatracker.ietf.org/doc/html/rfc7519#section-7.2). The payload is required to be a "valid JSON object", in this case it's a JSON string.

If you want to have custom behaviours when it comes to encoding and decoding there is something in the making in #460. But until that is finished the payload given will always be represented as a JSON object.

**Comment by vincentlkl** [comment]
Thanks @anakinj looking forward to that.

I will close this issue as there is a WIP Pr #460
