### ISSUE TITLE
Support JWK public URL 

### ISSUE THREAD

**Issue by santhanakarthikeyan** [jwt/ruby-jwt#473]
I've created a https://github.com/santhanakarthikeyan/ruby_jwk gem just to support public JWK URL. Could you migrate this feature over here https://github.com/santhanakarthikeyan/ruby_jwk/blob/main/app/controllers/concerns/ruby_jwk/authenticate.rb?

**Comment by anakinj** [comment]
Hi and thanks for the suggestion (and sorry for the late reply)

Im a little hesitant to include this kind of functionality to this gem because of the complexity of the matter, like caching of JWKs, http libs etc.

But as a separate GEM this kind of functionality would probably make sense.

**Comment by anakinj** [comment]
Will close this issue, loading external keys does not fit into this gem I think. 

But with this as inspiration I did something that can be attached to this gem.

https://github.com/anakinj/jwk-loader
