### ISSUE TITLE
Use OpenSSL 3

### ISSUE THREAD

**Issue by guillaumewrobel** [jwt/ruby-jwt#495]
[Heroku-22 stack](https://devcenter.heroku.com/articles/heroku-22-stack#openssl-3) has been released, and it does not support OpenSSL 1.1 but 3.0.

The `ruby-jwt` broke with the following error

> rsa#set_key= is incompatible with OpenSSL 3.0

`ruby-openssl`v3 [has been released](https://github.com/ruby/openssl/releases/tag/v3.0.0) and should be used

**Comment by anakinj** [comment]
Hi, just curious what version of the gem you are using? There was one fix for compatibility with OpenSSL 3.0 released in 2.4.0

Also this error reminds me of something that was fixed in #333

**Comment by ptiseo-tegria** [comment]
Just hit this problem with Ubuntu 22.04.1LTS and jwt 2.4.1

**Comment by anakinj** [comment]
Thanks for the report. 

Some kind of support for OpenSSL 3.0 will be shipped in the next release of this gem, would be great if someone would try the current master version in a real-world example.

**Comment by ptiseo-tegria** [comment]
@anakinj maybe I didn't understand, but my issue is a real-world codebase with the 2.4.1 master release? How else can I help?

**Comment by anakinj** [comment]
Sorry, was a little unclear. Current master being what is on GitHub that will eventually be something greater than 2.4.1, most probably 2.5.0.

The master branch very often contains features and fixes that has not been released yet, as in this case. So for example by looking at the differences from 2.4.1 master you can [compare the v2.4.1 tag with master](https://github.com/jwt/ruby-jwt/compare/v2.4.1...master). 

And by trying it out in a real-world example would mean to use the actual master branch of this repo in your codebase, specifying in your gemfile:

```
  gem 'jwt', github: 'jwt/ruby-jwt'
```

**Comment by ptiseo-tegria** [comment]
Np. Glad to assist. Made the change and got a different error:

```
/usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk/ec.rb:124:in `singleton class': undefined method `openssl_3?' for JWT:Module (NoMethodError)

        if ::JWT.openssl_3?
                ^^^^^^^^^^^
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk/ec.rb:92:in `<class:EC>'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk/ec.rb:7:in `<module:JWK>'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk/ec.rb:6:in `<module:JWT>'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk/ec.rb:5:in `<main>'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk.rb:50:in `require_relative'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt/jwk.rb:50:in `<main>'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/bundler/gems/ruby-jwt-0e7dcfacd822/lib/jwt.rb:9:in `<main>'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `each'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `each'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bundler-2.3.16/lib/bundler.rb:187:in `require'
        from /opt/XXXXXX/config/application.rb:19:in `<main>'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/command/actions.rb:22:in `require_application!'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/commands/runner/runner_command.rb:33:in `perform'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/share/rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by anakinj** [comment]
Super feedback! I'll take a look

**Comment by anakinj** [comment]
I think I've figured out the issue, fix applied in #504 

Could you `bundle update jwt` and try again and see what the next issue is? :)

**Comment by ptiseo-tegria** [comment]
Happy times, tokens are now being properly en/decoded on our API server. 🥳 Thanks a lot for your time!

**Comment by anakinj** [comment]
Great. Would suggest switching back to the official releases as soon as the next version is out.

Thanks for helping out to test this, the problem in #504 would probably not have not been caught before the next release and it would have affected everyone, not only the ones with openssl 3 installed.

**Comment by manrajtoor** [comment]
Hey @anakinj, any idea on when the next version, with this fix, will be rolled out?

**Comment by anakinj** [comment]
2.5.0 is out now with the openssl 3 adjustments

**Comment by anujkumarthakur** [comment]
> [Heroku-22 stack](https://devcenter.heroku.com/articles/heroku-22-stack#openssl-3) has been released, and it does not support OpenSSL 1.1 but 3.0.
> 
> The `ruby-jwt` broke with the following error
> 
> > rsa#set_key= is incompatible with OpenSSL 3.0
> 
> `ruby-openssl`v3 [has been released](https://github.com/ruby/openssl/releases/tag/v3.0.0) and should be used

I have same problem how can i solve it

**Comment by anakinj** [comment]
@anujkumarthakur could you specify a little, curious if there still is some issue.

As mentioned in my [last comment](https://github.com/jwt/ruby-jwt/issues/495#issuecomment-1228241996) `ruby-jwt` 2.5.0 was shipped with openssl3 support a few weeks back. Could you doublecheck the gem version you are using and if it's 2.5.0 and there is still some issues it would be nice with some additional information, like stacktraces and such.

**Comment by vartec** [comment]
Hi @anakinj, thanks for looking at this. 

I'm still having the issue even with 2.5.0. 

FYI, while running on [cimg/ruby:3.1.3](https://circleci.com/developer/images/image/cimg/ruby) (Ruby 3.1.3 on Ubuntu 22.04.1 with OpenSSL 3.0.2) I'm getting 
```ERROR -- : #<OpenSSL::PKey::PKeyError: rsa#set_key= is incompatible with OpenSSL 3.0>```

`bundle install` output:
```
Fetching jwt 2.5.0
Installing jwt 2.5.0
```

Corresponding `Gemfile.lock` line: 
```
   jwt (2.5.0)
```
