### ISSUE TITLE
Question: how to use Google API's JWKS uri when encoding JWT payload

### ISSUE THREAD

**Issue by mchavarriagam** [jwt/ruby-jwt#503]
Hi.

I'm currently working on an LTI Advantage implementation, which requires sending an encoded JWT from my platform to an external service. I've been following the LTI reference implementation (https://github.com/IMSGlobal/lti-reference-implementation) which encodes the JWT using the ruby-jwt library, like so:

`JWT.encode(@payload, @rsa_private, 'RS256', kid: @kid)`

The reference implementation uses a set of generated public and private keys, however the external service that I interact with only gives me the option to provide a public JWKS uri. So I'm using Google API's JWKS here: https://www.googleapis.com/oauth2/v3/certs

My question is, assuming the code above is the right way to go, how would I indicate that instead of an rsa private key, I want the JWT to be encoded with Google API's JWKS?

Thanks.

**Comment by anakinj** [comment]
Hi, not really liking issues being a place for questions. Maybe a better place for them would be the "Discussions" area.

Anyway, based on this info it's pretty hard to say what is supposed to happen and how.

Thinking that for sure some google oauth2 public keys will not help, technically it's probably possible to sign payloads with public keys but it would not make any sense. Encryption with the public keys on the other hands is a valid use-case.

Im guessing you need to generate a keypair and publish the public key via a public http uri somewhere. This uri is then to be provided to the service you are trying to access. Then you can generate signed tokens with the private key that the service then can validate using the public key uri you provided.

**Comment by mchavarriagam** [comment]
@anakinj my bad. Thanks.
