### ISSUE TITLE
Is there a way to ignore payload key ordering?

### ISSUE THREAD

**Issue by ekampp** [jwt/ruby-jwt#505]
Hey there. I found that hash-key order matters. Is this intentional?

I would expect these two JWT tokens to be the same:

```ruby
jwt1 = JWT.encode({ a: 1, b: 2 }, nil, "none")
# => "eyJhbGciOiJub25lIn0.eyJhIjoxLCJiIjoyfQ."

jwt2 = JWT.encode({ b: 2, a: 1 }, nil, "none")
# => "eyJhbGciOiJub25lIn0.eyJiIjoyLCJhIjoxfQ."
```

But they are, in fact, not the same. Note the `joy` vs. `jox` differences. 

In the above example, it's exemplified with no secret for the sake of simplicity. But when doing signature verification, this has a genuine impact. 

So, is this intentional? If yes, is there a mode/way to ignore the specific ordering of the payload keys? 

Thanks,
Emil

**Comment by anakinj** [comment]
If you want to be in control of the order the keys in the hash you either need to provide a sorted hash out of the original one for example like `{ b: 2, a: 1 }.sort.to_h` or use some custom hash implementation that has some other order logic. 

I think the default key order in a Ruby hash is the insertion order and therefore you see the behaviour you are describing.

This gem is not touching the hash that is given to it, just serializes it as JSON and base64 encodes the result.

A little curious in what kind of scenarios the order of the keys in the payload matter.

**Comment by anakinj** [comment]
Going to close this one. Lets reopen if still relevant.
