### ISSUE TITLE
JWK Parameters

### ISSUE THREAD

**Issue by bellebaum** [jwt/ruby-jwt#518]
Hey there :)

I was trying to use this gem, and the JWK implementation in particular, to handle any kind of cryptographic material for which I would normally go with several files in a format like PEM. This includes public and private key pairs, as well as certificates.
In principle, the JWK specs are built to handle all this kind of stuff, as can be seen e.g. in the [IANA registry](https://www.iana.org/assignments/jose/jose.xhtml#web-key-parameters).
Note in particular the `x5*` claims for certificates.

It would be nice if there were some option to include these parameters in `JWT::JWK` and have it be exported alongside the actual key values. Currently this is not the case, because most values (excluding `kid` and `kty`) are stored internally in an OpenSSL-compatible format (which is a good thing, I think, since cryptographic operations are often a lot more time-critical than serialization).

I do recognize that supporting the full set of semantics connected to these additional parameters may be a massive increase in scope for this project (e.g. any certificates in `x5c` must be signed by the next one in the array (let's not start talking about conformance to all X.509v3 extensions limiting who can sign what) with the first certificate referencing the very key in the JWK, and the `use` parameter should probably also be checked at some point or another).
A much more reasonable approach, if properly documented, would be to just allow people to add custom properties to the JWK. This is in a way similar to how this gem supports adding arbitrary claims to a JWT, but only actively provides guidance and validation for some of them (e.g. `iss`, `aud`, etc.).

The way I would envision this is by using the `options` argument in [KeyBase](https://github.com/jwt/ruby-jwt/blob/9b1a2eac9623a74669e2361e53338c4bba7e2ad3/lib/jwt/jwk/key_base.rb#L11) and just saving it after removing `key_generator` (note that `kid` is actually one of the custom parameters, and can be saved among them :) ).
When the JWK is later exported, any keys in the saved `options` are merged into the result.
One step up from this would be a method to access and manipulate these `options` (maybe even as usability-friendly `my_jwk['use']`).

I would be happy to hear some feedback on this idea and whether this endeavor and whether it may be beneficial to the project.

**Comment by anakinj** [comment]
Also the key accessor feels like a natural way to access JWK attributes. 👍 for that.

**Comment by anakinj** [comment]
Good points.

Are you interested in taking a shot on implementing something like this? Also open for pairing if you're into that :) 

Maybe starting with the `attrs` parts and excluding the hard parts as changing the key type or key parameters. Also the IANA list you provided is a pretty good reference for some validation on what can be combined with what.

**Comment by bellebaum** [comment]
I can send a PR your way probably on monday and mark you for a review. Maybe this is a helpful starting point for further discussions :)

**Comment by anakinj** [comment]
Lovely. Looking forward for that.
