### ISSUE TITLE
Unable to use JWT::JWK::Set

### ISSUE THREAD

**Issue by pedro-pedrosa** [jwt/ruby-jwt#533]
I'm reading through the docs and I see that I can use a `JWT::JWK::Set` to represent a set of JWKs and pass them to the `JWT.decode` method for validation purposed. however, I'm getting `NameError (uninitialized constant JWT::JWK::Set)` when I try to use it, and I see that the file here on this repo is 20-something days old while the last release was in august. so is this released? when can we expect this to be available?

I also don't suppose that the `jwks` param on `JWT.decode` works either so are there any viable workarounds in the meantime?

thank you.

**Comment by anakinj** [comment]
Hi, you are correct this feature is unfortunately not released just yet. As soon as someone has a little extra time to release a new version of the gem it will be available. Now when there is some demand there is slightly more motivation to spend a moment to make a new release :)

**Comment by anakinj** [comment]
Finally got around releasing `2.6.0` with the new JWK features.

**Comment by rywall** [comment]
@anakinj Thank you!
