### ISSUE TITLE
Missing JWK `alg` causes an error.

### ISSUE THREAD

**Issue by mroach** [jwt/ruby-jwt#534]
Hello!

I'm currently setting-up the bleeding-edge version of this gem to be able to validate tokens with public keys more easily.

I'm decoding a token issued by Microsoft Azure AD and I got an error:
```
/usr/local/bundle/bundler/gems/ruby-jwt-b478722acee3/lib/jwt/algos/algo_wrapper.rb:14:
in `valid_alg?': undefined method `casecmp' for nil:NilClass (NoMethodError)
```

Their JWK set: https://login.microsoftonline.com/common/discovery/v2.0/keys

The issue is that `alg` is missing from the keys. This seemed strange, but I checked the RFC for JWK and it turns out `alg` is optional: https://www.rfc-editor.org/rfc/rfc7517#section-4.4

The key that _is_ required is `kty`. According to the [JWA RFC], the values to expect here would be typically be `EC` or `RSA`.

Since I know what kind of keys the Microsoft ones are (at the moment), my workaround is to add `key[:alg] = "RS256"` to the keys before building the JWKS. 

The question is, what to do about this for a proper solution? I see there are more algorithms specified [in the gem](https://github.com/jwt/ruby-jwt/tree/main/lib/jwt/algos) than exist in the [JWA RFC].

I found [documentation from Curity](https://curity.io/resources/learn/jwt-signatures/#jwk) indicating that EDDSA would have `kty` of `"OKP"`. 

Then that leaves `RSASSA-PSS`. It looks like `oct` is the `kty` used for other kinds of algos that use symmetric keys. 

I haven't dived too deep into the gem code yet to figure out what's currently going on here, but it looks like that value is used to map to an algorithm class. I'm guessing the longer term solution is to use `kty` and possible sniffing at other attributes to get exact algorithms.

It may be worth noting another example where both `alg` and `kty` are included. Google Identity-Aware Proxy: https://www.gstatic.com/iap/verify/public_key-jwk

Before I dig much more, I wanted to see if you've encountered this before or have some ideas :)

[JWA RFC]: https://www.rfc-editor.org/rfc/rfc7518#page-28

**Comment by anakinj** [comment]
Great catch, I have a feeling this could be a regression. The alg header should not be that relevant anymore for the decoding part, the given list of algorithms are the ones with importance.

I don't think the alg missing from the JWKs is a problem but maybe it's missing from the token?

**Comment by mroach** [comment]
You're right that the `alg` missing from the JWK is apparently not a problem. I'm so far removed from the original problem that now I can't reproduce it properly which is a shame since I'm rather confused that adding the `alg` to the JWKs actually solved the problem before. Of course that's why bug reports 101 calls for including steps to reproduce; totally my bad there...

FWIW, here's a properly valid token from Azure AD and a demonstrating that it's fine as long as `algorithms` is included in the `decode` options.

```ruby
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJiMmFkMjFhMy0zZGUzLTRiMWYtOWRmYS1lNTU0NDYwMmQ2NWMiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNzNiOTAzZGEtMjcxYS00ZjIyLTk1ODYtNDIwN2NmODA1N2YwL3YyLjAiLCJpYXQiOjE2NjgwODc1NzMsIm5iZiI6MTY2ODA4NzU3MywiZXhwIjoxNjY4MDkxNDczLCJlbWFpbCI6IkFsZXhXQHgwc2ZwLm9ubWljcm9zb2Z0LmNvbSIsIm5hbWUiOiJBbGV4IFdpbGJlciIsIm5vbmNlIjoiNTU4NmZmNDktZDQwNS00ODgxLWE0MWQtNjYwYmNmYzk3Y2M5Iiwib2lkIjoiNWRiMTBmNDUtNDJmNy00ZDM0LWJjYzQtNzNhOTU0NTI3YzI1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiQWxleFdAeDBzZnAub25taWNyb3NvZnQuY29tIiwicmgiOiIwLkFYa0EyZ081Y3hvbklrLVZoa0lIejRCWDhLTWhyYkxqUFI5TG5mcmxWRVlDMWx5VUFHay4iLCJzdWIiOiJieGNQcFNUSGRCQ3pMSlBuR3J4MmJFM3FGZ3o5Nnk4eGo5UldTT2JpU2FvIiwidGlkIjoiNzNiOTAzZGEtMjcxYS00ZjIyLTk1ODYtNDIwN2NmODA1N2YwIiwidXRpIjoiZlk4bUNWMEUxRW1HQnRxSy1aYV9BQSIsInZlciI6IjIuMCJ9.Ccm-50HRkmMBsw0_8h1w6Te4m9nd0XNHJOhVvp4jGwrLEtN2Ya4UYJ5yyjUYTLSma9gGAIveJzkbVYaCHEn42CPuUIyMjvfZQwCKxQD-QLc6S3he0gbUQyrlt6jssokS5JcYfIfo0qYicvxkYxQuhKxYvruHk-UWsqxacZ_bj93OAli_Ia30Yc5JUF6mbXT8RsXAlyyHttZ1SW4gg5mm-JkVumo8ueaNEUDRaNzq7SdZcujtF2wChq5qmVonPoDlMy2FqpuDHPi8bwedZGTju6qMM0d__jswqhNAwaRp4iCnnCkvYP9c_6Hu02Cguzt4qqCqSEgyrglMEEJDu-mJYw"

# If you have Faraday or something similar. Otherwise, see the line after for the one key we need
# keys_hash = Faraday.get("https://login.microsoftonline.com/common/discovery/v2.0/keys").then { JSON.parse(_1.body) }
keys_hash = {"keys" => [
 {"kty"=>"RSA",                                                    
  "use"=>"sig",                                                    
  "kid"=>"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI",                            
  "x5t"=>"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI",                            
  "n"=>"wEMMJtj9yMQd8QS6Vnm538K5GN1Pr_I31_LUl9-OCYu-9_DrDvPGjViQK9kOiCjBfyqoAL-pBecn9-XXaS-C4xZTn1ZRw--GELabuo0u-U6r3TKj42xFDEP-_R5RpOGshoC95lrKiU5teuhn4fBM3XfR2GB0dVMcpzN3h4-0OMvBK__Zr9tkQCU_KzXTbNCjyA7ybtbr83NF9k3KjpTyOyY2S-qvFbY-AoqMhL9Rp8r2HBj_vrsr6RX6GeiSxxjbEzDFA2VIcSKbSHvbNBEeW2KjLXkz6QG2LjKz5XsYLp6kv_-k9lPQBy_V7Ci4ZkhAN-6j1S1Kcq58aLbp0wDNKQ",
  "e"=>"AQAB",                                                     
  "x5c"=>["MIIDBTCCAe2gAwIBAgIQH4FlYNA+UJlF0G3vy9ZrhTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIyMDUyMjIwMDI0OVoXDTI3MDUyMjIwMDI0OVowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMBDDCbY/cjEHfEEulZ5ud/CuRjdT6/yN9fy1JffjgmLvvfw6w7zxo1YkCvZDogowX8qqAC/qQXnJ/fl12kvguMWU59WUcPvhhC2m7qNLvlOq90yo+NsRQxD/v0eUaThrIaAveZayolObXroZ+HwTN130dhgdHVTHKczd4ePtDjLwSv/2a/bZEAlPys102zQo8gO8m7W6/NzRfZNyo6U8jsmNkvqrxW2PgKKjIS/UafK9hwY/767K+kV+hnokscY2xMwxQNlSHEim0h72zQRHltioy15M+kBti4ys+V7GC6epL//pPZT0Acv1ewouGZIQDfuo9UtSnKufGi26dMAzSkCAwEAAaMhMB8wHQYDVR0OBBYEFLFr+sjUQ+IdzGh3eaDkzue2qkTZMA0GCSqGSIb3DQEBCwUAA4IBAQCiVN2A6ErzBinGYafC7vFv5u1QD6nbvY32A8KycJwKWy1sa83CbLFbFi92SGkKyPZqMzVyQcF5aaRZpkPGqjhzM+iEfsR2RIf+/noZBlR/esINfBhk4oBruj7SY+kPjYzV03NeY0cfO4JEf6kXpCqRCgp9VDRM44GD8mUV/ooN+XZVFIWs5Gai8FGZX9H8ZSgkIKbxMbVOhisMqNhhp5U3fT7VPsl94rilJ8gKXP/KBbpldrfmOAdVDgUC+MHw3sSXSt+VnorB4DU4mUQLcMriQmbXdQc8d1HUZYZEkcKaSgbygHLtByOJF44XUsBotsTfZ4i/zVjnYcjgUQmwmAWD"],
  "issuer"=>"https://login.microsoftonline.com/{tenantid}/v2.0"}]}

jwks = JWT::JWK::Set.new(keys_hash)

JWT.decode(token, nil, true, { jwks:, verify_expiration: false, algorithms: ["RS256"] })
=>                          
[{"aud"=>"b2ad21a3-3de3-4b1f-9dfa-e5544602d65c",
  "iss"=>"https://login.microsoftonline.com/73b903da-271a-4f22-9586-4207cf8057f0/v2.0",
  "iat"=>1668087573,
  "nbf"=>1668087573,
  "exp"=>1668091473,
  "email"=>"AlexW@x0sfp.onmicrosoft.com",
  "name"=>"Alex Wilber",
  "nonce"=>"5586ff49-d405-4881-a41d-660bcfc97cc9",
  "oid"=>"5db10f45-42f7-4d34-bcc4-73a954527c25",
  "preferred_username"=>"AlexW@x0sfp.onmicrosoft.com",
  "rh"=>"0.AXkA2gO5cxonIk-VhkIHz4BX8KMhrbLjPR9LnfrlVEYC1lyUAGk.",
  "sub"=>"bxcPpSTHdBCzLJPnGrx2bE3qFgz96y8xj9RWSObiSao",
  "tid"=>"73b903da-271a-4f22-9586-4207cf8057f0",
  "uti"=>"fY8mCV0E1EmGBtqK-Za_AA",
  "ver"=>"2.0"},
 {"typ"=>"JWT", "alg"=>"RS256", "kid"=>"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"}]
```

**Comment by anakinj** [comment]
Im still puzzled on how you were able to get the failure you described:)

**Comment by mroach** [comment]
> Im still puzzled on how you were able to get the failure you described:)

Since I almost created the same problem for myself again, I think it may have been related to using this strategy from the README to auto-detect the `algorithms`: `algorithms = jwks.map { |key| key[:alg] }.compact.uniq`
That doesn't work with the [Microsoft JWKS](https://login.microsoftonline.com/common/discovery/v2.0/keys) since they do not include `alg`. 

What is the intended purpose of `algorithms`? Is there a reason not to hardcode `["ES256", "RS256"]` in my code for decoding tokens?
