### ISSUE TITLE
Are there breaking changes between 1.x and 2.x?

### ISSUE THREAD

**Issue by sdhull** [jwt/ruby-jwt#556]
Hello! First and foremost, thanks to all the contributors for this wonderful gem.

Second, I was just curious what precipitated changing the major version from 1.x to 2.x Typically (according to [semver](https://semver.org/), anyway) this is to indicate that there is a breaking change in the API. I perused the Changelog but nothing jumped out at me as a breaking change. Any light you could shed here would be very helpful as my org considers prioritizing upgrading this gem.

**Comment by anakinj** [comment]
I think your observations are correct, the documented API should be compatible between 1.x and 2.x. Not knowing the details about the reasoning back then it's hard to say why the major version bump.

**Comment by sdhull** [comment]
Thanks for your reply! That's encouraging from an upgrade standpoint. Not sure why I didn't close this last year, maybe I thought you would 🙈
